export type Ref={ref:string;type:string;note:string;source?:string;sourceRef?:string};
export type Verse={verse:number;text:string;refs?:Ref[]};
export type BookInfo={name:string;chapters:number;group:string};

export const library:BookInfo[]=[
{name:'Genesis',chapters:50,group:'Torah'},{name:'Exodus',chapters:40,group:'Torah'},{name:'Leviticus',chapters:27,group:'Torah'},{name:'Numbers',chapters:36,group:'Torah'},{name:'Deuteronomy',chapters:34,group:'Torah'},
{name:'Joshua',chapters:24,group:'History'},{name:'Judges',chapters:21,group:'History'},{name:'Ruth',chapters:4,group:'History'},{name:'1 Samuel',chapters:31,group:'History'},{name:'2 Samuel',chapters:24,group:'History'},{name:'1 Kings',chapters:22,group:'History'},{name:'2 Kings',chapters:25,group:'History'},{name:'1 Chronicles',chapters:29,group:'History'},{name:'2 Chronicles',chapters:36,group:'History'},{name:'Ezra',chapters:10,group:'History'},{name:'Nehemiah',chapters:13,group:'History'},{name:'Esther',chapters:10,group:'History'},
{name:'Job',chapters:42,group:'Wisdom'},{name:'Psalms',chapters:150,group:'Wisdom'},{name:'Proverbs',chapters:31,group:'Wisdom'},{name:'Ecclesiastes',chapters:12,group:'Wisdom'},{name:'Song of Songs',chapters:8,group:'Wisdom'},{name:'Wisdom',chapters:19,group:'Deuterocanonical expanded text'},{name:'Sirach',chapters:51,group:'Deuterocanonical expanded text'},
{name:'Isaiah',chapters:66,group:'Prophets'},{name:'Jeremiah',chapters:52,group:'Prophets'},{name:'Lamentations',chapters:5,group:'Prophets'},{name:'Ezekiel',chapters:48,group:'Prophets'},{name:'Daniel',chapters:12,group:'Prophets'},{name:'Hosea',chapters:14,group:'Prophets'},{name:'Joel',chapters:3,group:'Prophets'},{name:'Amos',chapters:9,group:'Prophets'},{name:'Obadiah',chapters:1,group:'Prophets'},{name:'Jonah',chapters:4,group:'Prophets'},{name:'Micah',chapters:7,group:'Prophets'},{name:'Nahum',chapters:3,group:'Prophets'},{name:'Habakkuk',chapters:3,group:'Prophets'},{name:'Zephaniah',chapters:3,group:'Prophets'},{name:'Haggai',chapters:2,group:'Prophets'},{name:'Zechariah',chapters:14,group:'Prophets'},{name:'Malachi',chapters:4,group:'Prophets'},
{name:'Matthew',chapters:28,group:'New Testament'},{name:'Mark',chapters:16,group:'New Testament'},{name:'Luke',chapters:24,group:'New Testament'},{name:'John',chapters:21,group:'New Testament'},{name:'Acts',chapters:28,group:'New Testament'},{name:'Romans',chapters:16,group:'New Testament'},{name:'1 Corinthians',chapters:16,group:'New Testament'},{name:'2 Corinthians',chapters:13,group:'New Testament'},{name:'Galatians',chapters:6,group:'New Testament'},{name:'Ephesians',chapters:6,group:'New Testament'},{name:'Philippians',chapters:4,group:'New Testament'},{name:'Colossians',chapters:4,group:'New Testament'},{name:'1 Thessalonians',chapters:5,group:'New Testament'},{name:'2 Thessalonians',chapters:3,group:'New Testament'},{name:'1 Timothy',chapters:6,group:'New Testament'},{name:'2 Timothy',chapters:4,group:'New Testament'},{name:'Titus',chapters:3,group:'New Testament'},{name:'Philemon',chapters:1,group:'New Testament'},{name:'Hebrews',chapters:13,group:'New Testament'},{name:'James',chapters:5,group:'New Testament'},{name:'1 Peter',chapters:5,group:'New Testament'},{name:'2 Peter',chapters:3,group:'New Testament'},{name:'1 John',chapters:5,group:'New Testament'},{name:'2 John',chapters:1,group:'New Testament'},{name:'3 John',chapters:1,group:'New Testament'},{name:'Jude',chapters:1,group:'New Testament'},{name:'Revelation',chapters:22,group:'New Testament'},
{name:'1 Enoch',chapters:108,group:'Ethiopian expanded text'},{name:'Jubilees',chapters:50,group:'Ethiopian expanded text'},{name:'1 Meqabyan',chapters:36,group:'Ethiopian expanded text'},{name:'2 Meqabyan',chapters:21,group:'Ethiopian expanded text'},{name:'3 Meqabyan',chapters:10,group:'Ethiopian expanded text'},{name:'Prayer of Manasseh',chapters:1,group:'Expanded text'},{name:'2 Enoch (Secrets of Enoch)',chapters:68,group:'Expanded text'},{name:'1 Esdras (Ezra Kali)',chapters:9,group:'Expanded text'},{name:'2 Esdras (Ezra Sutuel)',chapters:16,group:'Expanded text'},{name:'Tobit',chapters:14,group:'Expanded text'},{name:'Judith',chapters:16,group:'Expanded text'},{name:'Additions to Esther',chapters:6,group:'Expanded text'},{name:'Psalm 151',chapters:1,group:'Expanded text'},{name:'Baruch',chapters:5,group:'Expanded text'},{name:'Letter of Jeremiah',chapters:1,group:'Expanded text'},{name:'4 Baruch (Paralipomena of Jeremiah)',chapters:9,group:'Expanded text'},{name:'Prayer of Azariah / Song of the Three Holy Children',chapters:1,group:'Expanded text'},{name:'Susanna',chapters:1,group:'Expanded text'},{name:'Bel and the Dragon',chapters:1,group:'Expanded text'},{name:'1 Clement',chapters:65,group:'Expanded text'}];

export const expandedReaderConnected=new Set(['1 Enoch','Jubilees','1 Meqabyan','2 Meqabyan','3 Meqabyan','Prayer of Manasseh','2 Enoch (Secrets of Enoch)','1 Esdras (Ezra Kali)','2 Esdras (Ezra Sutuel)','Tobit','Judith','Additions to Esther','Psalm 151','Baruch','Letter of Jeremiah','4 Baruch (Paralipomena of Jeremiah)','Prayer of Azariah / Song of the Three Holy Children','Susanna','Bel and the Dragon','1 Clement','Wisdom','Sirach']);
export const sourceVerifiedExpanded=new Set(['Prayer of Manasseh','Psalm 151','Letter of Jeremiah']);
export const bookReaderStatus=(b:BookInfo)=>b.name==='1 Meqabyan'?'Reader connected · English chapters 1–7 currently available':(b.name==='2 Meqabyan'||b.name==='3 Meqabyan')?'Reader connected · complete current English source':b.group.includes('study')?'Study only · full reader not connected':(b.group.toLowerCase().includes('expanded')?(sourceVerifiedExpanded.has(b.name)?'Complete reader · source verified':expandedReaderConnected.has(b.name)?'Reader source connected · audit ongoing':'Reader source not connected'):'');

export const loaded:Record<string,Verse[]>={
'1 Enoch:1':[{verse:1,text:'The words of the blessing of Enoch, wherewith he blessed the elect and righteous, who will be living in the day of tribulation, when all the wicked and godless are to be removed.'},{verse:2,text:'And he took up his parable and said—Enoch a righteous man, whose eyes were opened by God, saw the vision of the Holy One in the heavens, which the angels showed me; and from them I heard everything, and from them I understood as I saw, but not for this generation, but for a remote one which is for to come.'},{verse:3,text:'Concerning the elect I said, and took up my parable concerning them: The Holy Great One will come forth from His dwelling.'},{verse:4,text:'And the eternal God will tread upon the earth, even on Mount Sinai, and appear in the strength of His might from the heaven of heavens.'},{verse:5,text:'And all shall be smitten with fear, and the Watchers shall quake, and great fear and trembling shall seize them unto the ends of the earth.'},{verse:6,text:'And the high mountains shall be shaken, and the high hills shall be made low, and shall melt like wax before the flame.'},{verse:7,text:'And the earth shall be wholly rent in sunder, and all that is upon the earth shall perish, and there shall be a judgement upon all men.'},{verse:8,text:'But with the righteous He will make peace, and will protect the elect, and mercy shall be upon them; and they shall all belong to God, and they shall be prospered, and they shall all be blessed; and He will help them all, and light shall appear unto them, and He will make peace with them.'},{verse:9,text:'And behold! He cometh with ten thousands of His holy ones to execute judgement upon all, and to destroy all the ungodly; and to convict all flesh of all the works of their ungodliness which they have ungodly committed, and of all the hard things which ungodly sinners have spoken against Him.'}],
'1 Enoch:2':[{verse:1,text:'Observe ye everything that takes place in the heaven, how they do not change their orbits, and the luminaries which are in the heaven, how they all rise and set in order each in its season, and transgress not against their appointed order.'},{verse:2,text:'Behold ye the earth, and give heed to the things which take place upon it from first to last, how steadfast they are, how none of the things upon earth change, but all the works of God appear to you.'},{verse:3,text:'Behold the summer and the winter, how the whole earth is filled with water, and clouds and dew and rain lie upon it.'}],
'1 Enoch:3':[{verse:1,text:'Observe and see how in the winter all the trees seem as though they had withered and shed all their leaves, except fourteen trees, which do not lose their foliage but retain the old foliage from two to three years till the new comes.'}],
'1 Enoch:4':[{verse:1,text:'And again, observe ye the days of summer how the sun is above the earth over against it. And you seek shade and shelter by reason of the heat of the sun, and the earth also burns with growing heat, and so you cannot tread on the earth, or on a rock by reason of its heat.'}],
'1 Enoch:5':[{verse:1,text:'Observe ye how the trees cover themselves with green leaves and bear fruit: wherefore give ye heed and know with regard to all His works, and recognize how He that liveth for ever hath made them so.'},{verse:2,text:'And all His works go on thus from year to year for ever, and all the tasks which they accomplish for Him, and their tasks change not, but according as God hath ordained so is it done.'},{verse:3,text:'And behold how the sea and the rivers in like manner accomplish and change not their tasks from His commandments.'},{verse:4,text:'But ye—ye have not been steadfast, nor done the commandments of the Lord, but ye have turned away and spoken proud and hard words with your impure mouths against His greatness.'},{verse:5,text:'Ye shall find no peace.'}],
'2 Enoch (Secrets of Enoch):1':[{verse:1,text:'There was a wise man, a great artificer, and the Lord conceived love for him and received him, that he should behold the uppermost dwellings and be an eye-witness of the wise and great and inconceivable and immutable realm of God Almighty.'},{verse:2,text:'At that time, he said, when my one hundred and sixty-fifth year was completed, I begat my son Mathusal.'},{verse:3,text:'After this too I lived two hundred years and completed of all the years of my life three hundred and sixty-five years.'},{verse:4,text:'On the first day of the month I was in my house alone and was resting on my bed and slept.'}],
'Prayer of Manasseh:1':[{verse:1,text:'O Lord Almighty, God of our fathers, of Abraham, Isaac, and Jacob, and of their righteous offspring;'},{verse:2,text:'you who have made heaven and earth, with all their order;'},{verse:3,text:'who have bound the sea by the word of your commandment; who have shut up the deep, and sealed it by your terrible and glorious name;'},{verse:4,text:'whom all things fear, yes, tremble before your power;'},{verse:5,text:'for the majesty of your glory cannot be borne, and the anger of your threatening toward sinners is unbearable;'},{verse:6,text:'your merciful promise is unmeasurable and unsearchable;'},{verse:7,text:'for you are the Lord Most High, of great compassion, patient and abundant in mercy, and you relent at human suffering.'},{verse:8,text:'You, O Lord, according to your great goodness have promised repentance and forgiveness to those who have sinned against you; and in the multitude of your mercies you have appointed repentance to sinners, that they may be saved.'},{verse:9,text:'I have sinned above the number of the sands of the sea. My transgressions are multiplied, O Lord, my transgressions are multiplied, and I am not worthy to behold or see the height of heaven for the multitude of my iniquities.'},{verse:10,text:'I am bowed down with many iron bands, so that I cannot lift up my head by reason of my sins, neither have I any relief; for I have provoked your wrath, and done that which is evil before you.'},{verse:11,text:'Now therefore I bow the knee of my heart, asking you for grace.'},{verse:12,text:'I have sinned, O Lord, I have sinned, and I acknowledge my iniquities;'},{verse:13,text:'but, I humbly ask you, forgive me, O Lord, forgive me, and please do not destroy me with my iniquities. Do not be angry with me forever, by reserving evil for me. Do not condemn me into the lower parts of the earth. For you, O Lord, are the God of those who repent.'},{verse:14,text:'In me you will show all your goodness, for you will save me, who am unworthy, according to your great mercy.'},{verse:15,text:'Then I will praise you forever all the days of my life; for all the army of heaven sings your praise, and yours is the glory forever and ever. Amen.'}],
'Wisdom:7':[{verse:7,text:'Therefore I prayed, and understanding was given me. I called on God, and the spirit of wisdom came to me.'}]
};