const webBookIds={Genesis:'GEN',Exodus:'EXO',Leviticus:'LEV',Numbers:'NUM',Deuteronomy:'DEU',Joshua:'JOS',Judges:'JDG',Ruth:'RUT','1 Samuel':'1SA','2 Samuel':'2SA','1 Kings':'1KI','2 Kings':'2KI','1 Chronicles':'1CH','2 Chronicles':'2CH',Ezra:'EZR',Nehemiah:'NEH',Esther:'EST',Job:'JOB',Psalms:'PSA',Proverbs:'PRO',Ecclesiastes:'ECC','Song of Songs':'SNG',Isaiah:'ISA',Jeremiah:'JER',Lamentations:'LAM',Ezekiel:'EZK',Daniel:'DAN',Hosea:'HOS',Joel:'JOL',Amos:'AMO',Obadiah:'OBA',Jonah:'JON',Micah:'MIC',Nahum:'NAM',Habakkuk:'HAB',Zephaniah:'ZEP',Haggai:'HAG',Zechariah:'ZEC',Malachi:'MAL',Matthew:'MAT',Mark:'MRK',Luke:'LUK',John:'JHN',Acts:'ACT',Romans:'ROM','1 Corinthians':'1CO','2 Corinthians':'2CO',Galatians:'GAL',Ephesians:'EPH',Philippians:'PHP',Colossians:'COL','1 Thessalonians':'1TH','2 Thessalonians':'2TH','1 Timothy':'1TI','2 Timothy':'2TI',Titus:'TIT',Philemon:'PHM',Hebrews:'HEB',James:'JAS','1 Peter':'1PE','2 Peter':'2PE','1 John':'1JN','2 John':'2JN','3 John':'3JN',Jude:'JUD',Revelation:'REV'};
const kjvNames={Wisdom:'Wisdom_of_Solomon',Sirach:'Wisdom_of_Sirach',Tobit:'Tobit',Judith:'Judith',Baruch:'Baruch','1 Esdras (Ezra Kali)':'I_Esdras','2 Esdras (Ezra Sutuel)':'II_Esdras','Additions to Esther':'Rest_of_Esther','Letter of Jeremiah':'Letter_of_Jeremiah','Prayer of Azariah / Song of the Three Holy Children':'Prayer_of_Azariah',Susanna:'Susanna','Bel and the Dragon':'Bel_and_the_Dragon'};
const kjvLimits={Wisdom:19,Sirach:51,Tobit:14,Judith:16,Baruch:5,'1 Esdras (Ezra Kali)':9,'2 Esdras (Ezra Sutuel)':16,'Additions to Esther':6,'Letter of Jeremiah':1,'Prayer of Azariah / Song of the Three Holy Children':1,Susanna:1,'Bel and the Dragon':1};
const meqabyanPages={'1 Meqabyan':'Translation:1_Meqabyan','2 Meqabyan':'Translation:2_Meqabyan','3 Meqabyan':'Translation:3_Meqabyan'};
const meqabyanLimits={'1 Meqabyan':7,'2 Meqabyan':21,'3 Meqabyan':10};
const decodeHtml=s=>s.replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&[a-zA-Z]+;/g,' ');
const clean=s=>decodeHtml(s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());
const wiki=async page=>{const u=`https://en.wikisource.org/w/api.php?action=parse&page=${encodeURIComponent(page)}&prop=text&format=json&formatversion=2`;const r=await fetch(u,{headers:{accept:'application/json','user-agent':'Word-and-Wisdom/2.0'}});if(!r.ok)throw new Error(`Wikisource ${r.status}`);const d=await r.json();return d.parse?.text||''};
const extractSupVerses=html=>{const marked=html.replace(/<sup[^>]*>\s*(\d{1,3})\s*<\/sup>/gi,' §§$1§§ ');const plain=clean(marked);const ms=[...plain.matchAll(/§§(\d{1,3})§§\s*/g)];return ms.map((m,i)=>({verse:Number(m[1]),text:plain.slice((m.index||0)+m[0].length,i+1<ms.length?(ms[i+1].index||plain.length):plain.length).trim()})).filter(v=>v.verse>0&&v.text).filter((v,i,a)=>i===0||v.verse>a[i-1].verse)};
const enoch=async ch=>{const html=await wiki(`The_Book_of_Enoch_(Charles)/Chapter_${String(ch).padStart(2,'0')}`);const plain=clean(html.replace(/<sup[^>]*class="reference"[\s\S]*?<\/sup>/gi,' '));const marker=plain.search(/CHAPTER\s+[IVXLCDM]+\.?/i);const body=(marker>=0?plain.slice(marker):plain).replace(/^CHAPTER\s+[IVXLCDM]+\.?\s*/i,'');const ms=[...body.matchAll(/(?:^|\s)(\d{1,3})\.\s+/g)];const verses=ms.map((m,i)=>({verse:Number(m[1]),text:body.slice((m.index||0)+m[0].length,i+1<ms.length?(ms[i+1].index||body.length):body.length).trim()})).filter(v=>v.text);if(!verses.length)throw new Error('1 Enoch unavailable');return verses};
const jubilees=async ch=>{const tref=encodeURIComponent(`Book of Jubilees.${ch}`);const version=encodeURIComponent('english|The Book of Jubilees, trans. R. H. Charles. London [1917]');const r=await fetch(`https://www.sefaria.org/api/v3/texts/${tref}?version=${version}&return_format=text_only`,{headers:{accept:'application/json','user-agent':'Word-and-Wisdom/2.0'}});if(!r.ok)throw new Error(`Sefaria ${r.status}`);const d=await r.json();const flat=x=>Array.isArray(x)?x.flatMap(flat):typeof x==='string'?[x]:[];const rows=flat(d.versions?.[0]?.text);const verses=rows.map((x,i)=>({verse:i+1,text:clean(x)})).filter(v=>v.text);if(!verses.length)throw new Error('Jubilees unavailable');return verses};
const parseMeqabyan=html=>{const heads=[...html.matchAll(/<h[1-4][^>]*>[\s\S]*?<\/h[1-4]>/gi)].map(m=>({m,n:Number(clean(m[0]).match(/Chapter\s+(\d{1,2})/i)?.[1]||0)})).filter(x=>x.n);const out={};for(let i=0;i<heads.length;i++){const start=(heads[i].m.index||0)+heads[i].m[0].length,end=i+1<heads.length?(heads[i+1].m.index||html.length):html.length;const plain=clean(html.slice(start,end).replace(/<sup[^>]*class=['"][^'"]*reference[^'"]*['"][\s\S]*?<\/sup>/gi,' '));const raw=[...plain.matchAll(/(?:^|\s)(?:\[(\d{1,3})\]|(\d{1,3})[.)]?)\s+/g)];let expected=1;const accepted=[];for(const m of raw){const n=Number(m[1]||m[2]);if(n===expected){accepted.push({n,index:m.index||0,end:(m.index||0)+m[0].length});expected++}}const verses=accepted.map((a,j)=>({verse:a.n,text:plain.slice(a.end,j+1<accepted.length?accepted[j+1].index:plain.length).trim()})).filter(v=>v.text);if(verses.length)out[heads[i].n]=verses}return out};
const meqabyan=async(book,ch)=>{const html=await wiki(meqabyanPages[book]);const chapters=parseMeqabyan(html);if(!chapters[ch])throw new Error('Meqabyan chapter unavailable');return chapters[ch]};
const apocrypha=async(book,ch)=>{const source=kjvNames[book];const sourceCh=book==='Additions to Esther'?ch+10:ch;const html=await wiki(`Bible_(King_James)/${source}`);const h=new RegExp(`<h2[^>]*>\\s*<span[^>]*id=['"]Chapter_${sourceCh}['"][^>]*>[\\s\\S]*?<\\/h2>`,'i').exec(html);let section=html;if(h&&h.index!==undefined){const rest=html.slice(h.index+h[0].length);const next=/<h2[^>]*>\s*<span[^>]*id=['"]Chapter_\d+['"]/i.exec(rest);section=next?rest.slice(0,next.index):rest}let verses=extractSupVerses(section).map(v=>({...v,text:v.text.replace(/^\[\s*edit\s*\]\s*/i,'').trim()})).filter(v=>v.text);if(!verses.length)throw new Error('Expanded chapter unavailable');return verses};
const prayer=["O Lord Almighty, God of our fathers, of Abraham, Isaac, and Jacob, and of their righteous offspring;","you who have made heaven and earth, with all their order;","who have bound the sea by the word of your commandment; who have shut up the deep, and sealed it by your terrible and glorious name;","whom all things fear, yes, tremble before your power;","for the majesty of your glory cannot be borne, and the anger of your threatening toward sinners is unbearable;","your merciful promise is unmeasurable and unsearchable;","for you are the Lord Most High, of great compassion, patient and abundant in mercy, and you relent at human suffering.","You, O Lord, according to your great goodness have promised repentance and forgiveness to those who have sinned against you; and in the multitude of your mercies you have appointed repentance to sinners, that they may be saved.","I have sinned above the number of the sands of the sea. My transgressions are multiplied, O Lord, my transgressions are multiplied, and I am not worthy to behold or see the height of heaven for the multitude of my iniquities.","I am bowed down with many iron bands, so that I cannot lift up my head by reason of my sins, neither have I any relief; for I have provoked your wrath, and done that which is evil before you.","Now therefore I bow the knee of my heart, asking you for grace.","I have sinned, O Lord, I have sinned, and I acknowledge my iniquities;","but, I humbly ask you, forgive me, O Lord, forgive me, and please do not destroy me with my iniquities. Do not be angry with me forever, by reserving evil for me. Do not condemn me into the lower parts of the earth. For you, O Lord, are the God of those who repent.","In me you will show all your goodness, for you will save me, who am unworthy, according to your great mercy.","Then I will praise you forever all the days of my life; for all the army of heaven sings your praise, and yours is the glory forever and ever. Amen."];
const ps151=["I was small among my brethren, and youngest in my father’s house: I tended my father’s sheep.","My hands formed a musical instrument, and my fingers tuned a psaltery.","And who shall tell my Lord? the Lord himself, he himself hears.","He sent forth his angel, and took me from my father’s sheep, and he anointed me with the oil of his anointing.","My brothers were handsome and tall; but the Lord did not take pleasure in them.","I went forth to meet the Philistine; and he cursed me by his idols.","But I drew his own sword, and beheaded him, and removed reproach from the children of Israel."];
const ok=(res,p)=>res.status(200).json(p);const fail=(res,status,error)=>res.status(status).json({error});
export default async function handler(req,res){
  if(req.method!=='GET')return fail(res,405,'Method not allowed');
  const book=String(req.query.book||'').trim(),ch=Number(req.query.chapter);
  if(!book||!Number.isInteger(ch)||ch<1)return fail(res,400,'Invalid book or chapter');
  try{
    if(book==='1 Enoch'){if(ch>108)return fail(res,404,'Chapter not available');return ok(res,{book,chapter:ch,translation:'R. H. Charles · public-domain edition via Wikisource',source:'Wikisource',verses:await enoch(ch)})}
    if(book==='Jubilees'){if(ch>50)return fail(res,404,'Chapter not available');return ok(res,{book,chapter:ch,translation:'R. H. Charles · public-domain edition via Sefaria',source:'Sefaria',verses:await jubilees(ch)})}
    if(meqabyanPages[book]){if(ch>meqabyanLimits[book])return fail(res,409,book==='1 Meqabyan'?'Current reusable English source covers chapters 1–7.':'Chapter not available');return ok(res,{book,chapter:ch,translation:'Wikisource community translation from Geʽez',source:'Wikisource',license:'CC BY-SA',verses:await meqabyan(book,ch)})}
    if(book==='Prayer of Manasseh'&&ch===1)return ok(res,{book,chapter:1,translation:'Public-domain English text',source:'Word & Wisdom verified chapter',verses:prayer.map((text,i)=>({verse:i+1,text}))});
    if(book==='Psalm 151'&&ch===1)return ok(res,{book,chapter:1,translation:'Brenton Septuagint · public domain',source:'Word & Wisdom verified chapter',verses:ps151.map((text,i)=>({verse:i+1,text}))});
    if(kjvNames[book]){if(ch>kjvLimits[book])return fail(res,404,'Chapter not available');return ok(res,{book,chapter:ch,translation:'King James Apocrypha · public-domain edition via Wikisource',source:'Wikisource',verses:await apocrypha(book,ch)})}
    const id=webBookIds[book];if(!id)return fail(res,404,'This book does not yet have a connected reader source');
    const r=await fetch(`https://bible-api.com/data/web/${id}/${ch}`,{headers:{accept:'application/json'}});if(!r.ok)return fail(res,r.status===404?404:502,'Bible source unavailable');const d=await r.json();const verses=(d.verses||[]).filter(v=>Number(v.chapter)===ch&&(!v.book_id||v.book_id===id)).map(v=>({verse:Number(v.verse),text:String(v.text||'').replace(/\s+/g,' ').trim()})).filter(v=>v.verse>0&&v.text);if(!verses.length)return fail(res,502,'Incomplete chapter returned by Scripture source');return ok(res,{book,chapter:ch,translation:d.translation?.name||'World English Bible',source:'bible-api.com',verses});
  }catch(err){console.error('Bible reader error',book,ch,err);return fail(res,502,err?.message||'Reader source unavailable')}
}
